server:
  port: 8080

### 通过下面配置启用所有的监控端点，默认情况下，这些端点是禁用的
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 如果 mysql帐号或密码错误，在项目启动的时候是不会报错的（因为底层采用懒加载）
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sfy?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: sfy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-boot-admin-server

## 注释
# actuator/info 相当于 在配置文件中，配置相关info 开头的配置信息
info:
  sfy:
    name: 邵
    home:
      phone: 1835
